// <auto-generated />
using System;
using ControlPlane.Infrastructure.AzureSql.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlPlane.Infrastructure.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260214193443_Migration_20260214_193438")]
    partial class Migration_20260214_193438
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbDeveloper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AzureObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DbRole")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbWorkSummaryJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExistingSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("TenantId");

                    b.ToTable("SummaryJobs");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbDeveloper", b =>
                {
                    b.HasOne("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbTenant", "DbTenant")
                        .WithMany("Developers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbTenant");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbUser", b =>
                {
                    b.HasOne("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbTenant", "DbTenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbTenant");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbWorkSummaryJob", b =>
                {
                    b.HasOne("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbDeveloper", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ControlPlane.Infrastructure.AzureSql.EfCore.Models.DbTenant", b =>
                {
                    b.Navigation("Developers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
